target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'ffmpeg-kit-ios-full-gpl', '~> 5.1'


    target 'iosAppTest' do
      inherit! :search_paths
      pod 'shared', :path => '../shared'
    end
end