name: iOS Tests

on: [ push ]

jobs:
  iOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: iOS set up
        uses: ./.github/actions/ios-set-up

      - name: Run iOS tests and capture logs
        run: xcodebuild build test -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' -verbose | tee output.log
        capture-output: true

      - name: Print test summary
        run: cat output.log | grep "Test Suite '.*' started at" -A14

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ios-test-logs
          path: ./output.log
