name: iOS Tests

on: [ push ]

jobs:
  iOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up  # Assuming you have this step defined

      - name: iOS set up
        uses: ./.github/actions/ios-set-up  # Assuming you have this step defined

      - name: Run iOS tests with log capturing and debug flag (corrected)
        run: xcodebuild build test -workspace iosApp/iosApp.xcworkspace \
          -configuration Debug \
          -scheme iosApp \ 
          -sdk iphoneos \
          -destination name='iPhone 14' \
          -verbose | tee output.log 2>&1 \
          build-settings[SWIFT_PACKAGE_DEBUG_FLAGS]=-DDEBUG

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ios-test-logs
          path: ./output.log

      - name: Check for errors
        run: echo "Exit code ${{ steps.run-tests.exit_code }}"  # Print the exit code
