name: Tests

on: [ push ]


jobs:
  iOS:
    #    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunIos == 'true' }}
    if: true
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: iOS set up
        uses: ./.github/actions/ios-set-up

      - run: xcodebuild build test -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' -verbose

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: "/Users/runner/Library/Developer/Xcode/DerivedData/*"
